# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: employee.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='employee.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x65mployee.proto\"\t\n\x07Nothing\"d\n\x08\x45mployee\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65signation\x18\x03 \x01(\t\x12\x0e\n\x06salary\x18\x04 \x01(\x02\x12\x19\n\ndepartment\x18\x05 \x01(\x0b\x32\x05.Dept\"\x1d\n\x0f\x45mployeeRequest\x12\n\n\x02id\x18\x01 \x01(\x05\";\n\x15\x45mployeeUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x16\n\x03\x65mp\x18\x02 \x01(\x0b\x32\t.Employee\" \n\x04\x44\x65pt\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x19\n\x0b\x44\x65ptRequest\x12\n\n\x02id\x18\x01 \x01(\x05\":\n\x11\x44\x65ptUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x19\n\ndepartment\x18\x02 \x01(\x0b\x32\x05.Dept\"\x1e\n\x0fResponseMessage\x12\x0b\n\x03msg\x18\x01 \x01(\t2\x8f\x02\n\x0f\x45mployeeService\x12,\n\x0bGetEmployee\x12\x10.EmployeeRequest\x1a\t.Employee\"\x00\x12*\n\x0fGetEmployeeList\x12\x08.Nothing\x1a\t.Employee\"\x00\x30\x01\x12,\n\x0bSetEmployee\x12\t.Employee\x1a\x10.ResponseMessage\"\x00\x12\x36\n\x0e\x44\x65leteEmployee\x12\x10.EmployeeRequest\x1a\x10.ResponseMessage\"\x00\x12<\n\x0eUpdateEmployee\x12\x16.EmployeeUpdateRequest\x1a\x10.ResponseMessage\"\x00\x32\xeb\x01\n\x0b\x44\x65ptService\x12 \n\x07GetDept\x12\x0c.DeptRequest\x1a\x05.Dept\"\x00\x12\"\n\x0bGetDeptList\x12\x08.Nothing\x1a\x05.Dept\"\x00\x30\x01\x12$\n\x07SetDept\x12\x05.Dept\x1a\x10.ResponseMessage\"\x00\x12\x34\n\x10\x44\x65leteDepartment\x12\x0c.DeptRequest\x1a\x10.ResponseMessage\"\x00\x12:\n\x10UpdateDepartment\x12\x12.DeptUpdateRequest\x1a\x10.ResponseMessage\"\x00\x62\x06proto3')
)




_NOTHING = _descriptor.Descriptor(
  name='Nothing',
  full_name='Nothing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=27,
)


_EMPLOYEE = _descriptor.Descriptor(
  name='Employee',
  full_name='Employee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Employee.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Employee.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='designation', full_name='Employee.designation', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='salary', full_name='Employee.salary', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='department', full_name='Employee.department', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=129,
)


_EMPLOYEEREQUEST = _descriptor.Descriptor(
  name='EmployeeRequest',
  full_name='EmployeeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='EmployeeRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=160,
)


_EMPLOYEEUPDATEREQUEST = _descriptor.Descriptor(
  name='EmployeeUpdateRequest',
  full_name='EmployeeUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='EmployeeUpdateRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='emp', full_name='EmployeeUpdateRequest.emp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=221,
)


_DEPT = _descriptor.Descriptor(
  name='Dept',
  full_name='Dept',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Dept.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Dept.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=255,
)


_DEPTREQUEST = _descriptor.Descriptor(
  name='DeptRequest',
  full_name='DeptRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DeptRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=282,
)


_DEPTUPDATEREQUEST = _descriptor.Descriptor(
  name='DeptUpdateRequest',
  full_name='DeptUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DeptUpdateRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='department', full_name='DeptUpdateRequest.department', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=342,
)


_RESPONSEMESSAGE = _descriptor.Descriptor(
  name='ResponseMessage',
  full_name='ResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='ResponseMessage.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=374,
)

_EMPLOYEE.fields_by_name['department'].message_type = _DEPT
_EMPLOYEEUPDATEREQUEST.fields_by_name['emp'].message_type = _EMPLOYEE
_DEPTUPDATEREQUEST.fields_by_name['department'].message_type = _DEPT
DESCRIPTOR.message_types_by_name['Nothing'] = _NOTHING
DESCRIPTOR.message_types_by_name['Employee'] = _EMPLOYEE
DESCRIPTOR.message_types_by_name['EmployeeRequest'] = _EMPLOYEEREQUEST
DESCRIPTOR.message_types_by_name['EmployeeUpdateRequest'] = _EMPLOYEEUPDATEREQUEST
DESCRIPTOR.message_types_by_name['Dept'] = _DEPT
DESCRIPTOR.message_types_by_name['DeptRequest'] = _DEPTREQUEST
DESCRIPTOR.message_types_by_name['DeptUpdateRequest'] = _DEPTUPDATEREQUEST
DESCRIPTOR.message_types_by_name['ResponseMessage'] = _RESPONSEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Nothing = _reflection.GeneratedProtocolMessageType('Nothing', (_message.Message,), dict(
  DESCRIPTOR = _NOTHING,
  __module__ = 'employee_pb2'
  # @@protoc_insertion_point(class_scope:Nothing)
  ))
_sym_db.RegisterMessage(Nothing)

Employee = _reflection.GeneratedProtocolMessageType('Employee', (_message.Message,), dict(
  DESCRIPTOR = _EMPLOYEE,
  __module__ = 'employee_pb2'
  # @@protoc_insertion_point(class_scope:Employee)
  ))
_sym_db.RegisterMessage(Employee)

EmployeeRequest = _reflection.GeneratedProtocolMessageType('EmployeeRequest', (_message.Message,), dict(
  DESCRIPTOR = _EMPLOYEEREQUEST,
  __module__ = 'employee_pb2'
  # @@protoc_insertion_point(class_scope:EmployeeRequest)
  ))
_sym_db.RegisterMessage(EmployeeRequest)

EmployeeUpdateRequest = _reflection.GeneratedProtocolMessageType('EmployeeUpdateRequest', (_message.Message,), dict(
  DESCRIPTOR = _EMPLOYEEUPDATEREQUEST,
  __module__ = 'employee_pb2'
  # @@protoc_insertion_point(class_scope:EmployeeUpdateRequest)
  ))
_sym_db.RegisterMessage(EmployeeUpdateRequest)

Dept = _reflection.GeneratedProtocolMessageType('Dept', (_message.Message,), dict(
  DESCRIPTOR = _DEPT,
  __module__ = 'employee_pb2'
  # @@protoc_insertion_point(class_scope:Dept)
  ))
_sym_db.RegisterMessage(Dept)

DeptRequest = _reflection.GeneratedProtocolMessageType('DeptRequest', (_message.Message,), dict(
  DESCRIPTOR = _DEPTREQUEST,
  __module__ = 'employee_pb2'
  # @@protoc_insertion_point(class_scope:DeptRequest)
  ))
_sym_db.RegisterMessage(DeptRequest)

DeptUpdateRequest = _reflection.GeneratedProtocolMessageType('DeptUpdateRequest', (_message.Message,), dict(
  DESCRIPTOR = _DEPTUPDATEREQUEST,
  __module__ = 'employee_pb2'
  # @@protoc_insertion_point(class_scope:DeptUpdateRequest)
  ))
_sym_db.RegisterMessage(DeptUpdateRequest)

ResponseMessage = _reflection.GeneratedProtocolMessageType('ResponseMessage', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEMESSAGE,
  __module__ = 'employee_pb2'
  # @@protoc_insertion_point(class_scope:ResponseMessage)
  ))
_sym_db.RegisterMessage(ResponseMessage)



_EMPLOYEESERVICE = _descriptor.ServiceDescriptor(
  name='EmployeeService',
  full_name='EmployeeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=377,
  serialized_end=648,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetEmployee',
    full_name='EmployeeService.GetEmployee',
    index=0,
    containing_service=None,
    input_type=_EMPLOYEEREQUEST,
    output_type=_EMPLOYEE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetEmployeeList',
    full_name='EmployeeService.GetEmployeeList',
    index=1,
    containing_service=None,
    input_type=_NOTHING,
    output_type=_EMPLOYEE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetEmployee',
    full_name='EmployeeService.SetEmployee',
    index=2,
    containing_service=None,
    input_type=_EMPLOYEE,
    output_type=_RESPONSEMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteEmployee',
    full_name='EmployeeService.DeleteEmployee',
    index=3,
    containing_service=None,
    input_type=_EMPLOYEEREQUEST,
    output_type=_RESPONSEMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateEmployee',
    full_name='EmployeeService.UpdateEmployee',
    index=4,
    containing_service=None,
    input_type=_EMPLOYEEUPDATEREQUEST,
    output_type=_RESPONSEMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMPLOYEESERVICE)

DESCRIPTOR.services_by_name['EmployeeService'] = _EMPLOYEESERVICE


_DEPTSERVICE = _descriptor.ServiceDescriptor(
  name='DeptService',
  full_name='DeptService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=651,
  serialized_end=886,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDept',
    full_name='DeptService.GetDept',
    index=0,
    containing_service=None,
    input_type=_DEPTREQUEST,
    output_type=_DEPT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetDeptList',
    full_name='DeptService.GetDeptList',
    index=1,
    containing_service=None,
    input_type=_NOTHING,
    output_type=_DEPT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetDept',
    full_name='DeptService.SetDept',
    index=2,
    containing_service=None,
    input_type=_DEPT,
    output_type=_RESPONSEMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteDepartment',
    full_name='DeptService.DeleteDepartment',
    index=3,
    containing_service=None,
    input_type=_DEPTREQUEST,
    output_type=_RESPONSEMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateDepartment',
    full_name='DeptService.UpdateDepartment',
    index=4,
    containing_service=None,
    input_type=_DEPTUPDATEREQUEST,
    output_type=_RESPONSEMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEPTSERVICE)

DESCRIPTOR.services_by_name['DeptService'] = _DEPTSERVICE

# @@protoc_insertion_point(module_scope)
