// Code generated by protoc-gen-go. DO NOT EDIT.
// source: employee.proto

package employee

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Employee struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Designation          string   `protobuf:"bytes,3,opt,name=designation,proto3" json:"designation,omitempty"`
	Salary               float32  `protobuf:"fixed32,4,opt,name=salary,proto3" json:"salary,omitempty"`
	Department           *Dept    `protobuf:"bytes,5,opt,name=department,proto3" json:"department,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{0}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Employee) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Employee) GetDesignation() string {
	if m != nil {
		return m.Designation
	}
	return ""
}

func (m *Employee) GetSalary() float32 {
	if m != nil {
		return m.Salary
	}
	return 0
}

func (m *Employee) GetDepartment() *Dept {
	if m != nil {
		return m.Department
	}
	return nil
}

type EmployeeRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmployeeRequest) Reset()         { *m = EmployeeRequest{} }
func (m *EmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*EmployeeRequest) ProtoMessage()    {}
func (*EmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{1}
}

func (m *EmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeRequest.Unmarshal(m, b)
}
func (m *EmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeRequest.Marshal(b, m, deterministic)
}
func (m *EmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeRequest.Merge(m, src)
}
func (m *EmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_EmployeeRequest.Size(m)
}
func (m *EmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeRequest proto.InternalMessageInfo

func (m *EmployeeRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Dept struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dept) Reset()         { *m = Dept{} }
func (m *Dept) String() string { return proto.CompactTextString(m) }
func (*Dept) ProtoMessage()    {}
func (*Dept) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb50a19aa79a6eac, []int{2}
}

func (m *Dept) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dept.Unmarshal(m, b)
}
func (m *Dept) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dept.Marshal(b, m, deterministic)
}
func (m *Dept) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dept.Merge(m, src)
}
func (m *Dept) XXX_Size() int {
	return xxx_messageInfo_Dept.Size(m)
}
func (m *Dept) XXX_DiscardUnknown() {
	xxx_messageInfo_Dept.DiscardUnknown(m)
}

var xxx_messageInfo_Dept proto.InternalMessageInfo

func (m *Dept) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Dept) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Employee)(nil), "Employee")
	proto.RegisterType((*EmployeeRequest)(nil), "EmployeeRequest")
	proto.RegisterType((*Dept)(nil), "Dept")
}

func init() { proto.RegisterFile("employee.proto", fileDescriptor_eb50a19aa79a6eac) }

var fileDescriptor_eb50a19aa79a6eac = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x41, 0x4a, 0xc5, 0x30,
	0x10, 0x86, 0x4d, 0x6c, 0x1f, 0x76, 0x0a, 0x55, 0xb2, 0x90, 0xe0, 0x2a, 0x06, 0x84, 0x20, 0xd2,
	0x45, 0x3d, 0x80, 0x1b, 0xc5, 0x7d, 0x3c, 0x41, 0x34, 0x83, 0x04, 0xda, 0x24, 0xa6, 0x51, 0xe8,
	0x29, 0xbc, 0xb2, 0x58, 0x6a, 0x2d, 0x5d, 0xbd, 0x5d, 0xf2, 0xfd, 0xcc, 0xcc, 0x37, 0x03, 0x0d,
	0x0e, 0xb1, 0x0f, 0x13, 0x62, 0x1b, 0x53, 0xc8, 0x41, 0x7e, 0x13, 0x38, 0x7b, 0x5a, 0x10, 0x6b,
	0x80, 0x3a, 0xcb, 0x89, 0x20, 0xaa, 0xd4, 0xd4, 0x59, 0xc6, 0xa0, 0xf0, 0x66, 0x40, 0x4e, 0x05,
	0x51, 0x95, 0x9e, 0xdf, 0x4c, 0x40, 0x6d, 0x71, 0x74, 0xef, 0xde, 0x64, 0x17, 0x3c, 0x3f, 0x9d,
	0xa3, 0x2d, 0x62, 0x97, 0x70, 0x18, 0x4d, 0x6f, 0xd2, 0xc4, 0x0b, 0x41, 0x14, 0xd5, 0xcb, 0x8f,
	0xdd, 0x00, 0x58, 0x8c, 0x26, 0xe5, 0x01, 0x7d, 0xe6, 0xa5, 0x20, 0xaa, 0xee, 0xca, 0xf6, 0x11,
	0x63, 0xd6, 0x9b, 0x40, 0x5e, 0xc3, 0xf9, 0x9f, 0x90, 0xc6, 0x8f, 0x4f, 0x1c, 0xf3, 0xde, 0x4b,
	0xde, 0x42, 0xf1, 0x5b, 0x76, 0x8c, 0x6f, 0xf7, 0xf0, 0xdf, 0xee, 0x05, 0xd3, 0x97, 0x7b, 0x43,
	0x76, 0x07, 0xf5, 0x33, 0xe6, 0x75, 0xeb, 0x8b, 0x76, 0x37, 0xef, 0xaa, 0x5a, 0x89, 0x3c, 0x79,
	0x3d, 0xcc, 0x87, 0xba, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x75, 0xbd, 0x82, 0xee, 0x3a, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmployeeServiceClient is the client API for EmployeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmployeeServiceClient interface {
	GetEmployee(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*Employee, error)
}

type employeeServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmployeeServiceClient(cc *grpc.ClientConn) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) GetEmployee(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*Employee, error) {
	out := new(Employee)
	err := c.cc.Invoke(ctx, "/EmployeeService/GetEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeServiceServer is the server API for EmployeeService service.
type EmployeeServiceServer interface {
	GetEmployee(context.Context, *EmployeeRequest) (*Employee, error)
}

// UnimplementedEmployeeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEmployeeServiceServer struct {
}

func (*UnimplementedEmployeeServiceServer) GetEmployee(ctx context.Context, req *EmployeeRequest) (*Employee, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployee not implemented")
}

func RegisterEmployeeServiceServer(s *grpc.Server, srv EmployeeServiceServer) {
	s.RegisterService(&_EmployeeService_serviceDesc, srv)
}

func _EmployeeService_GetEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmployeeService/GetEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetEmployee(ctx, req.(*EmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmployeeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmployee",
			Handler:    _EmployeeService_GetEmployee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "employee.proto",
}
